services:
  database_postgresql:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ../.env
      - .env
    networks:
      - traefik
networks:
  traefik:
    external: true