services:
  app_authentik_server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.4.1}
    restart: unless-stopped
    command: server
    labels:
      traefik.enable: true
      traefik.http.routers.authentik.priority: 50
      traefik.http.routers.authentik.rule: Host(`auth.${TOP_LEVEL_DOMAIN}`) || HostRegexp(`{subdomain:[a-z0-9-]+}.${TOP_LEVEL_DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)
      traefik.http.routers.authentik.entrypoints: websecure
      traefik.http.services.authentik.loadbalancer.server.port: 9000
      traefik.http.routers.authentik.tls.certresolver: letsencrypt
    ports:
      - "9000:9000"
    environment:
      AUTHENTIK_REDIS__HOST: ${REDIS_HOST:-app_authentik_redis}
    volumes:
      - ./data/media:/media
      - ./data/custom-templates:/templates
    env_file:
      - ../.env
      - .env
    networks:
      - authentik
      - traefik
  app_authentik_worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.4.1}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: ${REDIS_HOST:-app_authentik_redis}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/media:/media
      - ./data/certs:/certs
      - ./data/custom-templates:/templates
    env_file:
      - ../.env
      - .env
    networks:
      - authentik
      - traefik
  app_authentik_proxy:
    image: ghcr.io/goauthentik/proxy:${AUTHENTIK_TAG:-2025.4.1}
    environment:
      AUTHENTIK_HOST: https://app_authentik_server:9000
      AUTHENTIK_HOST_BROWSER: http://auth.${TOP_LEVEL_DOMAIN}
    env_file:
      - ../.env
      - .env
    labels:
      traefik.enable: true
      traefik.port: 9000
      traefik.http.middlewares.authentik.forwardauth.address: http://app_authentik_server:9000/outpost.goauthentik.io/auth/traefik
      traefik.http.middlewares.authentik.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.authentik.forwardauth.authResponseHeaders: X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version
    restart: unless-stopped
    networks:
      - authentik
      - traefik
    depends_on:
      app_authentik_server:
        condition: service_healthy
  app_authentik_redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    env_file:
      - ../.env
      - .env
    volumes:
      - ./data_redis:/data
    networks:
      - authentik
networks:
  traefik:
    external: true
  authentik:
    external: true